name: CI/CD Pipeline - v7

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build_and_push:

  deploy2dockerhub:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Pull and run Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/web_ip_python:${{ github.sha }}
        docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/web_ip_python:${{ github.sha }}
